import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Navbar/Nav";

export const metadata = {
  title: "Project 4",
  description: "Generated by Project 4",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-blue-50 via-purple-50 to-pink-100">
        <Nav />
        {children}
      </body>
    </html>
  );
}
